### PR TITLE
Changing our API keeping the version isolated and maintainable.

### PR DESCRIPTION
**Pull request by samuelcastro**

### CODE REVIEW

**Comment by leomcabral** [comment]
I liked the use of a configuration, but the documentation (jsdoc or whatever is called the /** */ comment) that generate the swagger ui will not be updated. I can not provide a good solution, but I saw a hapi pluigin to manage api version. Take a look https://www.npmjs.com/package/hapi-api-version

this plugin can take an easier aproach to manage the API versions within the same running application (the way you proposed).

For now I think you can merge this pull request to dev, and in a later we discuss about the api version handling.

**Comment by samuelcastro** [comment]
Nope, you're wrong.
Whenever you update the configuration file (Development, Production or Test) ALL endpoints will be automatically updated.

I like this way to versioning our api because, sometime we need to create a endpoint and maintain the last one and doesn't make sense for me setup a new server.

We are not using jsdoc to generate the swagger UI, everything is synchronised, if you update any service/endpoint, the API UI will be updated automatically as well. ;)

**Comment by samuelcastro** [comment]
Regarding that plugin, it is doing the same thing that I've created basically. 

Our approach is more dynamic because we are centralizing our version controle in our place.

I'm going to merge that pull request and you can see by yourself.

**Comment by leomcabral** [comment]
I thought the hapi-swagger plugin is using the jsdoc to generate the doc site. If it don't use it better.

**Comment by samuelcastro** [comment]
We won't have this problem, because as I said, we are integrating the API itself directly with the UI page.

**Comment by leomcabral** [comment]
Cool. So we can remove the version number in the comments.

**Comment by samuelcastro** [comment]
We could remove, I just added it to have an example, doesn't matter there.

**Pull request merged**
